Отрефакторил код подсчёта сходства
TreetonOrg/Treeton pull request #3
Opened 2017-06-27 20:11 UTC by IlyaGusev

2017-08-17 11:33 UTC, anatoli-starostin requested changes
Про averageFootnessMode договаривались, что ты его отовсюду выпилишь. И коэффициенты протащи через конфиг. И еще вопрос: ты задействовал новые данные от Максима?

2017-08-17 11:33 UTC, anatoli-starostin commented on dev/prosody/src/treeton/prosody/musimatix/PreciseVerseDistanceCounter.java
> +        regressionCoef[4] = 1.0868493902627618; // Константа
Вроде договаривались, что коэффициенты протащишь через конфиг файл

2017-08-17 11:35 UTC, IlyaGusev commented on dev/prosody/src/treeton/prosody/musimatix/PreciseVerseDistanceCounter.java
> +        regressionCoef[4] = 1.0868493902627618; // Константа
Ок, довыпилю, коэффициенты протащу. Да, это с учётом новых данных

2017-08-19 15:27 UTC, anatoli-starostin approved these changes

2017-08-19 16:01 UTC, merged